# This file was generated by GoReleaser. DO NOT EDIT.
cask "tallyfy" do
  version "0.1.2"

  on_macos do
    on_intel do
      sha256 "fb87fded38bc1fd35aac62a113afdbaa0e6596ea76cfe7885c8e2562d7f64e3d"
      url "https://github.com/tallyfy/cli/releases/download/v#{version}/tallyfy_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "660f2b9645ca358412ddcf164286652b3301b6b2c66857d6fe1a6d446928c273"
      url "https://github.com/tallyfy/cli/releases/download/v#{version}/tallyfy_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "d8a0aa378d28454ea27f2cb5eb906e60baf673f10dee523667fb90eea007dfaa"
      url "https://github.com/tallyfy/cli/releases/download/v#{version}/tallyfy_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "11eee7398c97f912211113b9f519e362abf1502a97fe4c8b976a82be458e6718"
      url "https://github.com/tallyfy/cli/releases/download/v#{version}/tallyfy_#{version}_linux_arm64.tar.gz"
    end
  end

  name "tallyfy"
  desc "Command-line interface for Tallyfy - deterministic workflow automation"
  homepage "https://tallyfy.com"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tallyfy"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/tallyfy"]
    end
  end

  # No zap stanza required

end
