# This file was generated by GoReleaser. DO NOT EDIT.
cask "tallyfy" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "3628432a3fcf5ffa278c3107d9157b0615300caa59907fd9d545990800a75d70"
      url "https://github.com/tallyfy/cli/releases/download/v#{version}/tallyfy_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "1c26b164d1da73486acd8223eebf12857a1702386ac7caca317853cddb082507"
      url "https://github.com/tallyfy/cli/releases/download/v#{version}/tallyfy_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "34f201d0060252a6e3b204d6a312322f2b519141d7462bb984f2eb14f77bef7c"
      url "https://github.com/tallyfy/cli/releases/download/v#{version}/tallyfy_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "a0a9b1523728dbe4f9411533a8d53e371b25a4ab25ed7526b986056521a55837"
      url "https://github.com/tallyfy/cli/releases/download/v#{version}/tallyfy_#{version}_linux_arm64.tar.gz"
    end
  end

  name "tallyfy"
  desc "Command-line interface for Tallyfy - deterministic workflow automation"
  homepage "https://tallyfy.com"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tallyfy"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/tallyfy"]
    end
  end

  # No zap stanza required

end
