# This file was generated by GoReleaser. DO NOT EDIT.
cask "tallyfy" do
  version "0.1.1"

  on_macos do
    on_intel do
      sha256 "a7830ba38375ceaf489879e64ceb480075fcf5d997cf7a4dd614b63c4cb95257"
      url "https://github.com/tallyfy/cli/releases/download/v#{version}/tallyfy_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "e26aa9d8f4c973714d56458364e50ccb20f0d7cee4f9a51d8e937a360b7aacaa"
      url "https://github.com/tallyfy/cli/releases/download/v#{version}/tallyfy_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "46fe4df097b9b6e5fd8c441a93863bb61dcecd914a6c49dac9eacff7cab0be66"
      url "https://github.com/tallyfy/cli/releases/download/v#{version}/tallyfy_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "3ca5bf519e34b7fc576046efbd4a779a729ebde8221ed87a8e38850eeb4c0dfe"
      url "https://github.com/tallyfy/cli/releases/download/v#{version}/tallyfy_#{version}_linux_arm64.tar.gz"
    end
  end

  name "tallyfy"
  desc "Command-line interface for Tallyfy - deterministic workflow automation"
  homepage "https://tallyfy.com"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tallyfy"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/tallyfy"]
    end
  end

  # No zap stanza required

end
